language: node_js
node_js:
  - 10
env:
  - CI_BEFORE_COMMIT_SHA=${TRAVIS_COMMIT}

cache:
  directories:
    - ~/.npm

before_install:
  - echo ${TRAVIS_COMMIT_RANGE}
  - mv ci.npmrc .npmrc

before_script:
  - yarn ng version

script:
  - yarn ci:commitlint
  - yarn ci:lint
  - yarn ci:test
  - yarn ci:build

after_success:
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
